$ErrorActionPreference = 'Stop'

Write-Host 'This script intentionally contains no secrets.'
Write-Host 'Set user environment variables manually or in a private password manager shell:'
Write-Host '  FEISHU_APP_ID'
Write-Host '  FEISHU_APP_SECRET'
Write-Host '  FEISHU_ALLOWED_OPEN_IDS'
Write-Host '  CLAUDE_BIN'
Write-Host '  OBSIDIAN_API_KEY'
Write-Host '  OBSIDIAN_PORT'
Write-Host ''
Write-Host 'Current required non-secret defaults:'
Write-Host '  FEISHU_ALLOWED_OPEN_IDS=ou_59a5d4b0cc115a66295961a1aec66a9e'
Write-Host '  CLAUDE_BIN=C:\Users\maoxu\AppData\Local\Microsoft\WinGet\Packages\Anthropic.ClaudeCode_Microsoft.Winget.Source_8wekyb3d8bbwe\claude.exe'
Write-Host '  OBSIDIAN_PORT=27123'
